### ISSUE TITLE
Jest snapshot testing

### ISSUE THREAD

**Issue by sandeshds** [nosir/cleave.js#296]
I see an error while trying to write a snapshot test.

`TypeError: Cannot read property 'selectionEnd' of null`
`at Object.updateValueState (node_modules/season-web-components/node_modules/cleave.js/dist/cleave-react.js:423:36)
      at Object.onInput (node_modules/season-web-components/node_modules/cleave.js/dist/cleave-react.js:366:16)
      at Object.init (node_modules/season-web-components/node_modules/cleave.js/dist/cleave-react.js:164:16)
      at Object.componentDidMount (node_modules/season-web-components/node_modules/cleave.js/dist/cleave-react.js:75:15)
      at Object.chainedFunction [as componentDidMount] (node_modules/season-web-components/node_modules/cleave.js/dist/cleave-react.js:1147:12)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:262:25
      at measureLifeCyclePerf (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:73:12)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:261:11
      at CallbackQueue.notifyAll (node_modules/react-test-renderer/lib/CallbackQueue.js:74:22)
      at ReactTestReconcileTransaction.close (node_modules/react-test-renderer/lib/ReactTestReconcileTransaction.js:34:26)
      at ReactTestReconcileTransaction.closeAll (node_modules/react-test-renderer/lib/Transaction.js:207:25)
      at ReactTestReconcileTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:154:16)
      at batchedMountComponentIntoNode (node_modules/react-test-renderer/lib/ReactTestMount.js:67:27)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:141:20)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactDefaultBatchingStrategy.js:60:26)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactUpdates.js:95:27)
      at Object.render [as create] (node_modules/react-test-renderer/lib/ReactTestMount.js:126:18)`

**Comment by nosir** [comment]
I think there was a fix release for this: https://github.com/nosir/cleave.js/issues/223
Which version you are using?

**Comment by nosir** [comment]
Okay, it's been a while, closing this, feel free to open if the error still pops up in the latest release.

**Comment by pedrolauro** [comment]
Hi. Getting the same error while trying to render with `react-test-renderer`:

```
import renderer from 'react-test-renderer'
...
// DateInput contains Cleave component
test('DateInput should match snapshot', () => {
  const result = renderer.create(<DateInput {...propsFromSomewhere} />)
  expect(result).toMatchSnapshot()
})
```

```
Error: Uncaught [TypeError: Cannot read property 'selectionEnd' of null]
        at reportException (node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
        at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:209:9)
        at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
        at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
        at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
        at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
        at Object.invokeGuardedCallbackDev (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2424:16)
        at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2477:31)
        at commitRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10862:7)
        at node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12313:5 

TypeError: Cannot read property 'selectionEnd' of null
        at Object.updateValueState (node_modules/cleave.js/dist/cleave-react-node.js:458:37)
        at Object.onInput (node_modules/cleave.js/dist/cleave-react-node.js:423:16)
        at Object.init (node_modules/cleave.js/dist/cleave-react-node.js:166:20)
        at Object.componentDidMount (node_modules/cleave.js/dist/cleave-react-node.js:76:15)
        at Object.chainedFunction [as componentDidMount] (node_modules/cleave.js/dist/cleave-react-node.js:1176:12)
        at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9253:22)
        at commitAllLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10650:7)
        at HTMLUnknownElement.callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2374:14)
        at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
        at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
        at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
        at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
        at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
        at Object.invokeGuardedCallbackDev (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2424:16)
        at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2477:31)
        at commitRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10862:7)
        at node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12313:5
        at Object.unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:255:12)
        at completeRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12312:13)
        at performWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12241:9)
        at performWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12149:7)
        at performSyncWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12123:3)
        at requestWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11992:5)
        at scheduleWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11807:5)
        at scheduleRootUpdate (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12406:3)
        at updateContainerAtExpirationTime (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12434:10)
        at updateContainer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12445:10)
        at Object.create (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12878:5)
        at Object.create (src/components/Field/__tests__/Field.test.js:79:27)
        at Object.asyncJestTest (node_modules/jest-jasmine2/build/jasmine_async.js:108:37)
        at resolve (node_modules/jest-jasmine2/build/queue_runner.js:56:12)
        at new Promise (<anonymous>)
        at mapper (node_modules/jest-jasmine2/build/queue_runner.js:43:19)
        at promise.then (node_modules/jest-jasmine2/build/queue_runner.js:87:41)
        at process._tickCallback (internal/process/next_tick.js:68:7)
```

So I checked out this `TypeError: Cannot read property 'selectionEnd' of null
        at Object.updateValueState (node_modules/cleave.js/dist/cleave-react-node.js:458:37)
` method. My analysis is really shallow, but maybe that's a problem:

```
...
if (!owner.element) {
   owner.setState({ value: pps.result });
}

var endPos = owner.element.selectionEnd;
var oldValue = owner.element.value;
var newValue = pps.result;
...
```
`owner` is not null, but `element` is (for my test, anyway). Shouldn't be a `return` inside that `if`?

**Comment by joelmoss** [comment]
I can second this. I'm getting this same error with react.

**Comment by nosir** [comment]
Hi @joelmoss @pedrolauro it is fixed here in May, thanks.
https://github.com/nosir/cleave.js/pull/461
