### ISSUE TITLE
Cleave React: Jest Cleave snapshot testing throws error

### ISSUE THREAD

**Issue by pc-vmora** [nosir/cleave.js#460]
When I try to test react component using Jest snapshot I see this error

```
Cannot read property 'selectionEnd' of null

TypeError: Cannot read property 'selectionEnd' of null
    at Object.updateValueState (eval at ue (https://codesandbox.io/static/js/sandbox.776e962a.js:1:162661), <anonymous>:462:37)
    at Object.onInput (eval at ue (https://codesandbox.io/static/js/sandbox.776e962a.js:1:162661), <anonymous>:375:20)
    at Object.init (eval at ue (https://codesandbox.io/static/js/sandbox.776e962a.js:1:162661), <anonymous>:166:20)
    at Object.componentDidMount (eval at ue (https://codesandbox.io/static/js/sandbox.776e962a.js:1:162661), <anonymous>:76:15)
    at Object.chainedFunction [as componentDidMount] (eval at ue (https://codesandbox.io/static/js/sandbox.776e962a.js:1:162661), <anonymous>:1180:12)
    at eval (https://7k98m09n41.codesandbox.io/node_modules/react-test-renderer/lib/ReactCompositeComponent.js:264:25)
    at measureLifeCyclePerf (https://7k98m09n41.codesandbox.io/node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:12)
    at eval (https://7k98m09n41.codesandbox.io/node_modules/react-test-renderer/lib/ReactCompositeComponent.js:263:11)
    at CallbackQueue.notifyAll (https://7k98m09n41.codesandbox.io/node_modules/react-test-renderer/lib/CallbackQueue.js:76:22)
    at ReactTestReconcileTransaction.close (https://7k98m09n41.codesandbox.io/node_modules/react-test-renderer/lib/ReactTestReconcileTransaction.js:36:26)
    at ReactTestReconcileTransaction.closeAll (https://7k98m09n41.codesandbox.io/node_modules/react-test-renderer/lib/Transaction.js:209:25)
    at ReactTestReconcileTransaction.perform (https://7k98m09n41.codesandbox.io/node_modules/react-test-renderer/lib/Transaction.js:156:16)
    at batchedMountComponentIntoNode (https://7k98m09n41.codesandbox.io/node_modules/react-test-renderer/lib/ReactTestMount.js:69:27)
    at ReactDefaultBatchingStrategyTransaction.perform (https://7k98m09n41.codesandbox.io/node_modules/react-test-renderer/lib/Transaction.js:143:20)
    at Object.batchedUpdates (https://7k98m09n41.codesandbox.io/node_modules/react-test-renderer/lib/ReactDefaultBatchingStrategy.js:62:26)
    at Object.batchedUpdates (https://7k98m09n41.codesandbox.io/node_modules/react-test-renderer/lib/ReactUpdates.js:97:27)
    at Object.render [as create] (https://7k98m09n41.codesandbox.io/node_modules/react-test-renderer/lib/ReactTestMount.js:128:18)
    at Object.eval (https://7k98m09n41.codesandbox.io/index.test.js:19:44)
    at https://codesandbox.io/static/js/vendors~sandbox.331151cd.chunk.js:1:177708
    at new Promise (<anonymous>)
    at t.callAsyncFn (https://codesandbox.io/static/js/vendors~sandbox.331151cd.chunk.js:1:177371)
    at https://codesandbox.io/static/js/sandbox.776e962a.js:1:192436
    at g (https://codesandbox.io/static/js/common-sandbox.3445291d.chunk.js:1:387899)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.3445291d.chunk.js:1:387687)
    at Generator.e.(anonymous function) [as next] (https://codesandbox.io/static/js/common-sandbox.3445291d.chunk.js:1:388078)
    at t (https://codesandbox.io/static/js/common-sandbox.3445291d.chunk.js:1:379157)
    at u (https://codesandbox.io/static/js/common-sandbox.3445291d.chunk.js:1:379367)
    at https://codesandbox.io/static/js/common-sandbox.3445291d.chunk.js:1:379426
    at new Promise (<anonymous>)
    at https://codesandbox.io/static/js/common-sandbox.3445291d.chunk.js:1:379308
    at https://codesandbox.io/static/js/sandbox.776e962a.js:1:192699
    at https://codesandbox.io/static/js/sandbox.776e962a.js:1:191179
    at g (https://codesandbox.io/static/js/common-sandbox.3445291d.chunk.js:1:387899)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.3445291d.chunk.js:1:387687)
    at Generator.e.(anonymous function) [as next] (https://codesandbox.io/static/js/common-sandbox.3445291d.chunk.js:1:388078)
    at t (https://codesandbox.io/static/js/common-sandbox.3445291d.chunk.js:1:379157)
    at u (https://codesandbox.io/static/js/common-sandbox.3445291d.chunk.js:1:379367)
    at https://codesandbox.io/static/js/common-sandbox.3445291d.chunk.js:1:379426
    at new Promise (<anonymous>)
    at https://codesandbox.io/static/js/common-sandbox.3445291d.chunk.js:1:379308
    at https://codesandbox.io/static/js/sandbox.776e962a.js:1:191721
    at https://codesandbox.io/static/js/sandbox.776e962a.js:1:189045
    at g (https://codesandbox.io/static/js/common-sandbox.3445291d.chunk.js:1:387899)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.3445291d.chunk.js:1:387687)
    at Generator.e.(anonymous function) [as next] (https://codesandbox.io/static/js/common-sandbox.3445291d.chunk.js:1:388078)
    at t (https://codesandbox.io/static/js/common-sandbox.3445291d.chunk.js:1:379157)
    at u (https://codesandbox.io/static/js/common-sandbox.3445291d.chunk.js:1:379367)
    at https://codesandbox.io/static/js/common-sandbox.3445291d.chunk.js:1:379426
    at new Promise (<anonymous>)
    at https://codesandbox.io/static/js/common-sandbox.3445291d.chunk.js:1:379308
Filter
```

The issue is reproduced on code sandbox 👉  https://codesandbox.io/s/7k98m09n41

**Comment by pc-vmora** [comment]
[Pull Request](https://github.com/nosir/cleave.js/pull/461) is created to fix this issue.

**Comment by nosir** [comment]
Thanks. Released in https://github.com/nosir/cleave.js/releases/tag/v1.5.0
Cheers
