### ISSUE TITLE
undefined is not an object (evaluating 'e.slice') 

### ISSUE THREAD

**Issue by ekilah** [nosir/cleave.js#601]
After upgrading to `1.6.0` from `1.4.10` as a part of working around https://github.com/nosir/cleave.js/issues/593 , I have now seen this come up twice in bug reports:

```
TypeError undefined is not an object (evaluating 'e.slice') 
    ../node_modules/cleave.js/dist/cleave-react-node.js:2536 getPostDelimiter
    ../node_modules/cleave.js/dist/cleave-react-node.js:344 onChange
    [native code] onChange
    ../node_modules/react-dom/cjs/react-dom.production.min.js:15:202 ka
    ../node_modules/react-dom/cjs/react-dom.production.min.js:15:355 qa
    ../node_modules/react-dom/cjs/react-dom.production.min.js:16:31 ra
    ../node_modules/react-dom/cjs/react-dom.production.min.js:16:235 wa
    ../node_modules/react-dom/cjs/react-dom.production.min.js:17:239 Aa
    [native code] forEach
    ../node_modules/react-dom/cjs/react-dom.production.min.js:17:19 ya
    ../node_modules/react-dom/cjs/react-dom.production.min.js:17:411 Ba
    ../node_modules/react-dom/cjs/react-dom.production.min.js:85:402 Pd
    ../node_modules/react-dom/cjs/react-dom.production.min.js:87:246 Ud
    [native code] Be
    ../node_modules/scheduler/cjs/scheduler.production.min.js:20:126 
    ../node_modules/react-dom/cjs/react-dom.production.min.js:207:389 fj
    ../node_modules/react-dom/cjs/react-dom.production.min.js:86:239 Sd
    [native code] je
```

I haven't figured out how to reproduce it yet, but the relevant code seems to have been changed recently at https://github.com/nosir/cleave.js/pull/582

So far the bug has happened on this device:

```
Safari 13.0.5
en-US
Mac OS X 10.15
```

**Comment by ekilah** [comment]
there's a chance @CmdrRamon will understand, if @nosir doesn't see it first

**Comment by hugobally** [comment]
I'm having the same issue, you can repro by right clicking an empty input field and pasting from clipboard - `lastInputValue` is undefined which causes the exception. Any update on this ?

**Comment by ekilah** [comment]
@hugobally oh cool, glad someone could figure out how to reproduce. 

If you want a fix and don't need the `rawValue` functionality, I worked around it in a fork and it has been stable for the last couple weeks.

To add the fork in your `package.json` dependencies, for example:

```
"cleave.js": "https://github.com/MercuryTechnologies/cleave.js.git#rawValueFix1.4.10",
```

This fork reverts `cleave.js` to 1.4.10` - where this issue doesn't occur anymore - and also fixes #593 (as long as you don't need the `rawValue` from this library.

We'll see if the live version gets a fix, but until then, hope that helps!

**Comment by psiclopz** [comment]
I was also able to reproduce this consistently by clicking into an empty cleave field, and then clicking on a different window altogether (off the browser).

**Comment by rythos42** [comment]
Sounds like the repro steps are understood, but we get this from an extension one of our developers made that auto-fills in a form and just started getting this when we upgraded to 1.6.

I'm going to downgrade to 1.5.10 where it looks like this error won't exist, until this issue is resolved! Thanks.

**Comment by rogorman9** [comment]
Just to add another case for this, I'm getting what I think is a related bug when I try to use Enzyme's `simulate` function to simulate a change event on the native `input` element within a Jest unit test. The error I'm getting in this case is: 
```
TypeError: Cannot read property 'slice' of undefined

at Object.getPostDelimiter (node_modules/cleave.js/dist/cleave-react-node.js:2536:27)
      at Object.onChange (node_modules/cleave.js/dist/cleave-react-node.js:344:35)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:362:14)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:411:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:466:31)
      at invokeGuardedCallbackAndCatchFirstError (node_modules/react-dom/cjs/react-dom.development.js:480:25)
      at executeDispatch (node_modules/react-dom/cjs/react-dom.development.js:612:3)
      at executeDispatchesInOrder (node_modules/react-dom/cjs/react-dom.development.js:637:5)
      at executeDispatchesAndRelease (node_modules/react-dom/cjs/react-dom.development.js:743:5)
      at executeDispatchesAndReleaseTopLevel (node_modules/react-dom/cjs/react-dom.development.js:752:10)
      at forEachAccumulated (node_modules/react-dom/cjs/react-dom.development.js:724:8)
      at runEventsInBatch (node_modules/react-dom/cjs/react-dom.development.js:769:3)
      at node_modules/react-dom/cjs/react-dom-test-utils.development.js:1596:7
      at Object.batchedUpdates$1 [as unstable_batchedUpdates] (node_modules/react-dom/cjs/react-dom.development.js:24328:12)
      at node_modules/react-dom/cjs/react-dom-test-utils.development.js:1592:14
      at eventFn (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:540:11)
      at fn (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:404:37)
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:24328:12)
      at Object.act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1120:14)
      at act (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:404:13)
      at Object.wrapAct [as simulateEvent] (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:539:9)
      at ReactWrapper.simulateEvent (node_modules/enzyme/src/ReactWrapper.js:666:22)
      at ReactWrapper.call [as single] (node_modules/enzyme/src/ReactWrapper.js:1170:21)
      at ReactWrapper.single [as simulate] (node_modules/enzyme/src/ReactWrapper.js:665:17)
      at simulate (src/utilities/tests/enzymeUtilities.js:29:13)
      at Object.<anonymous> (src/components/openNewAccountFormFlow/personalInformation.test.js:589:9)

  ● <PersonalInformation /> › Inline Errors › Date of Birth Field › displays error state when field is set to blank

    TypeError: Cannot read property 'slice' of undefined

      27 | 
      28 | export function fillInput(component: ShallowWrapper<*> | ReactWrapper<*>, content: string) {
    > 29 |   component.simulate('change', { target: { value: content } });
         |             ^
      30 |   component.simulate('blur');
      31 | }
      32 | 

      at Object.getPostDelimiter (node_modules/cleave.js/dist/cleave-react-node.js:2536:27)
      at Object.onChange (node_modules/cleave.js/dist/cleave-react-node.js:344:35)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:362:14)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:411:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:466:31)
      at invokeGuardedCallbackAndCatchFirstError (node_modules/react-dom/cjs/react-dom.development.js:480:25)
      at executeDispatch (node_modules/react-dom/cjs/react-dom.development.js:612:3)
      at executeDispatchesInOrder (node_modules/react-dom/cjs/react-dom.development.js:637:5)
      at executeDispatchesAndRelease (node_modules/react-dom/cjs/react-dom.development.js:743:5)
      at executeDispatchesAndReleaseTopLevel (node_modules/react-dom/cjs/react-dom.development.js:752:10)
      at forEachAccumulated (node_modules/react-dom/cjs/react-dom.development.js:724:8)
      at runEventsInBatch (node_modules/react-dom/cjs/react-dom.development.js:769:3)
      at node_modules/react-dom/cjs/react-dom-test-utils.development.js:1596:7
      at Object.batchedUpdates$1 [as unstable_batchedUpdates] (node_modules/react-dom/cjs/react-dom.development.js:24328:12)
      at node_modules/react-dom/cjs/react-dom-test-utils.development.js:1592:14
      at eventFn (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:540:11)
      at fn (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:404:37)
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:24328:12)
      at Object.act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1120:14)
      at act (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:404:13)
      at Object.wrapAct [as simulateEvent] (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:539:9)
      at ReactWrapper.simulateEvent (node_modules/enzyme/src/ReactWrapper.js:666:22)
      at ReactWrapper.call [as single] (node_modules/enzyme/src/ReactWrapper.js:1170:21)
      at ReactWrapper.single [as simulate] (node_modules/enzyme/src/ReactWrapper.js:665:17)
      at simulate (src/utilities/tests/enzymeUtilities.js:29:13)
```

**Comment by Discartyptics** [comment]
I can confirm I am having this same issue in v1.6.0.

**Comment by damianthekreeeytor** [comment]
Also ran into this issue using 1.6.0 and I can confirm that downgrading until the issue has been resolved is an acceptable workaround.

**Comment by sudosubin** [comment]
I encountered the same issue, but I did not want to downgrade the Cleave.js version. The issue is that `lastInputValue` is undefined untill the first input, so I just initialized it with empty string. (using `onInit` method)

```typescript
import { ComponentProps } from 'react';
import Cleave from 'cleave.js/react';

const onInit: ComponentProps<typeof Cleave>['onInit'] = (owner) => {
  (owner as any).lastInputValue = '';
};

const WrappedCleave = (props: any) => {
  return (
    <Cleave
      onInit={onInit}
      {...props}
    />
  )
};
```

Now it works for me. Any comment would be welcome.

**Comment by psiclopz** [comment]
The WrappedCleave component was a good idea, but it does not fix the issue I encountered with the getPostDelimiter function call being called twice with null followed by the value.

**Comment by 0xc0d3r** [comment]
@nosir @ekilah  Any update and reliable work-arounds for this?

**Comment by ekilah** [comment]
Please read the whole thread. I posted a workaround above: https://github.com/nosir/cleave.js/issues/601#issuecomment-653132114

We've been using this workaround since I posted it, with no further issues.
